project:
  type: book
  resources:
    - staticwebapp.config.json

book:
  title: "Living Guide to Data at IMPACT Initiatives"
  author: "Iyed GHEDAMSI"
  date: "7/9/2025"
  chapters:
    - index.qmd
    - chapters/intro.qmd
    - chapters/01_version_control.qmd
    - chapters/summary.qmd
    - chapters/references.qmd

bibliography: references.bib

format:
  html:
    theme:
      - cosmo
      - brand
